### ISSUE TITLE
LED Common Type?

### ISSUE THREAD

**Issue by adammhaile** [ScholliYT/LED-Matrix-16x16#5]
Really just a question... I wanted to confirm, are the LEDs you used Common anode? I believe that's what you need for the TLC5940 but wasn't sure if that swapped when using the shift registers to multiplex it all?

**Comment by ScholliYT** [comment]
I used the standard 5050 SMD RGB Leds. They have 3 anodes and 3 cathodes. I then soldered all 3 anodes together which then connect to a shift register. The 3 cathodes connect each to one pin on the TLC

**Comment by adammhaile** [comment]
Awesome. Thanks :)

**Comment by ScholliYT** [comment]
Close
