### ISSUE TITLE
High side transistor type?

### ISSUE THREAD

**Issue by okh-mzny** [ScholliYT/LED-Matrix-16x16#7]
I'm looking to build a comparable Matrix.
I have a single color and an STP16CPS05 as a sink driver, I'm looking to switch about 30mA per LED with a total of 480mA per transistor. What kind of transistor did you use in your design? The transistors aren't marked on your schematic :/

Thank you

**Comment by ScholliYT** [comment]
We used SS8050 transistors in the first design. However, we built a completely new pcb with different components. We used AO3415A mosfets instead of transistors for switching.
